# Generated by Django 4.2.6 on 2023-11-17 01:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photopost",
            old_name="Category",
            new_name="category",
        ),
    ]
